stages:
  - deploy

pages:
  stage: deploy
  artifacts:
    paths:
      - "public"
  script:
    - mkdir -v .public
    - cp -fv debian-flyers.pages.debian.net/pages/* .public/
    - mv -v .public public
